version: '3.8'

services:
  test_api:
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file:
      - .env.test
    depends_on:
      mysql_test:
        condition: service_healthy
    networks:
      - test-network

  mysql_test:
    image: mysql:8.0
    container_name: mysql_test
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - test-network

networks:
  test-network:
    driver: bridge 