FROM node:18-alpine

WORKDIR /app

# Install dependencies
RUN apk add --no-cache \
    python3 \
    make \
    g++ \
    build-base \
    openssl \
    openssl-dev \
    libc6-compat

# Copy only the necessary files to install dependencies
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy prisma files
COPY prisma ./prisma/

# Generate prisma client
RUN npx prisma generate

# Copy the rest of the files
COPY . .

# Run e2e tests
CMD ["npm", "run", "test:e2e"]
