export enum ApiErrorCode {
  // Auth errors - 4xx
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_USER_NOT_FOUND = 'AUTH_USER_NOT_FOUND',
  AUTH_USER_ALREADY_EXISTS = 'AUTH_USER_ALREADY_EXISTS',

  // Validation errors
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  // Server errors - 5xx
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  DATABASE_ERROR = 'SERVER_002',

  // Authorization errors
  FORBIDDEN = 'FORBIDDEN',

  // Resource errors
  NOT_FOUND = 'NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  FLAG_NOT_FOUND = 'FLAG_NOT_FOUND',
  BANK_NOT_FOUND = 'BANK_NOT_FOUND',
  CREDIT_CARD_NOT_FOUND = 'CREDIT_CARD_NOT_FOUND',
  CARD_NAME_ALREADY_EXISTS = 'CARD_NAME_ALREADY_EXISTS',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',

  // Token errors
  TOKEN_INVALID = 'TOKEN_INVALID',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_ACCESS_INVALID = 'TOKEN_ACCESS_INVALID',
  TOKEN_REFRESH_INVALID = 'TOKEN_REFRESH_INVALID',
  TOKEN_REFRESH_EXPIRED = 'TOKEN_REFRESH_EXPIRED',
  TOKEN_DECODE_ERROR = 'TOKEN_DECODE_ERROR',
}
